openapi: 3.0.0
info:
  title: Students Compass
  description: >
    Great API for students looking for a place to stay and spend your spare time
    on.
  termsOfService: http://swagger.io/terms/
  contact:
    email: studentscompass007@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0.1-oas3
tags:
  - name: accomodations
    description: Everything about places where to live
  - name: restaurants
    description: Places where to eat and drink
  - name: culture
  - name: recreational
    description: Places and events for entertainment
paths:
  /accomodations:
    get:
      tags:
        - accomodations
      summary: Returns all accomodations in the system.
      responses:
        '200':
          description: Successful
    post:
      tags:
        - accomodations
      responses:
        '200':
          description: Successful
  /accomodations/{accId}:
    put:
      tags:
        - accomodations
      parameters:
        - name: accId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
    delete:
      tags:
        - accomodations
      parameters:
        - name: accId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
  /restaurants:
    get:
      tags:
        - restaurants
      responses:
        '200':
          description: Successful
    post:
      tags:
        - restaurants
      responses:
        '200':
          description: Successful
  /restaurants/{restId}:
    put:
      tags:
        - restaurants
      parameters:
        - name: restId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
    delete:
      tags:
        - restaurants
      parameters:
        - name: restId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
  /culture:
    get:
      tags:
        - culture
      responses:
        '200':
          description: Successful
    post:
      tags:
        - culture
      responses:
        '200':
          description: Successful
  /culture/{cultureId}:
    put:
      tags:
        - culture
      responses:
        '200':
          description: Successful
      parameters:
        - name: cultureId
          in: path
          required: true
          schema:
            type: integer
    delete:
      tags:
        - culture
      parameters:
        - name: cultureId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
  /recreational:
    get:
      tags:
        - recreational
      responses:
        '200':
          description: Successful
    post:
      tags:
        - recreational
      responses:
        '200':
          description: Successful
  /recreational/{recId}:
    put:
      tags:
        - recreational
      parameters:
        - name: recId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
    delete:
      tags:
        - recreational
      parameters:
        - name: recId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful
    
components:
  schemas:
    Accomodation:
      type: object
      properties:
        id:
          type: integer
    Restaurant:
      type: object
      properties:
        id:
          type: integer
    Culture:
      type: object
      properties:
        id:
          type: integer
    Recreational:
      type: object
      properties:
        id:
          type: integer
  requestBodies:
    Accomodation:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Accomodation'
    Restaurant:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Restaurant'
    Recreational:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Recreational'
    Culture:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Culture'
